# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8601089839c47146dd369cb78a6aed0b1d414218017c8550fe324da93ceea4e18614585863b97f2e75c1ba937fe8db5d8f7601939e36e6594615df6bace3468

test:
  secret_key_base: e3fd99091c94ffe6b1f6f7e008adabd14d0d991bc660e7329bbade5e9ff44f60c5185b41a9698793b2110b7e5f5656c9a3fb7249cd6c221bb9a5a883c783236f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
